name: HT-Login
version: 1.21.11
main: com.htlogin.HTLogin
api-version: 1.13
author: mustafa8907
description: Professional login system.

commands:
  gir:
    aliases: [login, l]
  kayıt:
    aliases: [register, reg]
  logout:
  changepassword:
